In [ ]:
import numpy as np


In [ ]:
list =[1,2,3,4,5]   # with this list advantageis to create only 1 d array 
print(list)

In [3]:
# advantages of numpy is array over list 
import numpy as np 
print("1d array")
a = np.array([1,2,3,4,5,8])
print(a ) 

1d array
[1 2 3 4 5 8]


In [5]:
print("2d array")
import numpy as np
c=np.array([[1,2,3,4],[1234,44,53,32]])
print(c)


2d array
[[   1    2    3    4]
 [1234   44   53   32]]


In [7]:
print("3d array")
import numpy as np
d=np.array([[[1,2,3,4],[1,34,5,68],[1,2,3,4]]])
print(d)

3d array
[[[ 1  2  3  4]
  [ 1 34  5 68]
  [ 1  2  3  4]]]


In [9]:
type(d)

numpy.ndarray

In [11]:
print(a.size)

6


In [17]:
print(d.shape)

(1, 3, 4)


In [19]:
print(d.dtype)

int32


In [21]:
d.transpose()

array([[[ 1],
        [ 1],
        [ 1]],

       [[ 2],
        [34],
        [ 2]],

       [[ 3],
        [ 5],
        [ 3]],

       [[ 4],
        [68],
        [ 4]]])

In [ ]:
# numpy is a python library for numeric and scientific computing  it stands for numerical python and consists of mlti dimensional array objects 
numpy allows you to perform varios operations on array including 
* array slicing 
array join 
array split 
array reshape 
array filter 


In [23]:
import numpy as np
n=np.array((1,2,3))
print(n)

[1 2 3]


In [ ]:
# dimensions of an array in numpy are also called the rank of an array 
with that we will also see some examples to create 0d , 1d ,2d, arrays 
create a zero dimensional numpy array 
create a one dimensional numpy array 


In [27]:
import numpy as np
n=np.array(24)
print("dimension=" , n.ndim)

dimension= 0


In [31]:
import numpy as np
n= np.array([1,2,3,4])
print(n)
print(n.ndim)

[1 2 3 4]
1


In [35]:
import numpy as np
d = np.array([[12,3,4,5],[1234,3,23,23]])
print(d)
print(d.ndim)

[[  12    3    4    5]
 [1234    3   23   23]]
2


In [37]:
import numpy as np
d = np.array([[[[[4]]]]])
print(d)
print(d.ndim)

[[[[[4]]]]]
5


In [ ]:
# initialize numpy arrays 
to initialize numpy arrays we can use the numpy.zero() method useing this method initialize numpy array with zero 


In [41]:
import numpy as np
n=np.zeros([2,3])
print(n)
print(type(n))

[[0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>


In [43]:
import numpy as np
n=np.zeros([4,4])
print(n)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# data types in numpy 
python numpy supports the folloing data types 
b - boolean 
u unsigned integer 
f float 
c complex float 
m time delta 
M- datetime 
s string 

# let us see some exMPLE 
get the datatype of a numpy array with integer 
get the data type ofa numpy array with string 
set the dattype size within a numpy array 
convert one datatype to another 


In [47]:
import numpy as np
n = np.array([1,2,3,4])
print(n.dtype)

int32


In [49]:
import numpy as np
n = np.array(['amit','rohit','asjn','adjbc'])
print(n)
print(n.dtype)

['amit' 'rohit' 'asjn' 'adjbc']
<U5


In [53]:
import numpy as np
n=np.array(['10','23','23'])
print(n)
print(n.dtype)
n2=n.astype('i')

['10' '23' '23']
<U2


In [ ]:
#Numpy array indexing 
array indexing is accessing array elements in numpy access an array element using the index number 


In [ ]:
index 0 element 1 
index 1 element 2 so on 

# example 1 Access the 1st elemrnt (index 0) from a one dimensional array 
# example 2 Access the 4 th element (index 3 ) from a one domensional


In [55]:

import numpy as np
n=np.array([10,20,30,40])
print(n)
print(n[0])

[10 20 30 40]
10


In [57]:
# index in 1d array 
import numpy as np
n=np.array([12,23,45,67,78])
print(n[4])

78


In [61]:

# now indexing in 2d array 
import numpy as np
n=np.array([[1,2,3,4],[12,34,12,45]])
print(n)
print(n[0,1])
print(n[1,3])


[[ 1  2  3  4]
 [12 34 12 45]]
2
45


In [77]:
# now indexing in 3d array 
import numpy as np
n = np.array([[[1,2,3,4],[12,23,45,67],[21,31,41,51]]])
print(n.ndim)


3


In [79]:
import numpy as np
n=np.array([[[2,3,5],[2,3,4]],[[32,45,78],[89,34,23]]])
print(n)
print(n[0,0,0])
print(n[0,0,1])

[[[ 2  3  5]
  [ 2  3  4]]

 [[32 45 78]
  [89 34 23]]]
2
3


In [ ]:
# access the last element from a 1d array with negative indexing 
# Access the last element from a 2d array with negative indexing 


In [81]:
import numpy as np
n=np.array([2,3,4])
print("last elemnent=",n[-1])

last elemnent= 4


In [83]:
# 2d array with negative indexing 
import numpy as np
n=np.array([[1,2,3],[34,23,67]])
print(n)
print(n[0,-1])
print(n[1,-1])

[[ 1  2  3]
 [34 23 67]]
3
67


In [ ]:
# numpy slicing 
slicing the array in a range from start to end is what we call array slicing 


In [ ]:
# arr[start:end]
the following array slicing example we will run
slicing from index 1 to 3 
slicing from index 2 to 5 
slicing from 5 to last 
slicing from the begining to index 5 


In [87]:
import numpy as np
n=np.array([20,23,232,234,123,543,322,123,24])
print(n[1:3])

[ 23 232]


In [89]:
import numpy as np
d = np.array([12,1,2,34,5,67])
print(n[2:5])

[232 234 123]


In [93]:
import numpy as np
n=np.array([1,2,3,4,5,67,8,90])
print(n[5:])

[67  8 90]


In [97]:
import numpy as np
n=np.array([1,2,3,4,5,6,7,8,9,9])
print(n[:5])

[1 2 3 4 5]


In [ ]:
# we can also include steps while slicing step means a jup of elements if the step is 2 that means 2 jumps for the next element 

In [ ]:
arr[star:end:step]

In [101]:
import numpy as np
c = np.array([1,23,4,45,6,767])
print(c[1:5:2])

[23 45]


In [ ]:
the following are the example to slice two  dimensional arrays 
@ slicing from index 2 to 5 
@ slicing for both the dimensions 


In [103]:
import numpy as np
s=np.array([[1,2,3,4,5,6,6],[1,2,3,4,5,54]])
print(s[0,2:5])


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
# numpy isa python library used for working with arrays 
numpy stands for nuerical python 
# WHY use numpy
in python we have list that serve the purpose of arrays but they are sloww to processs 

Numpy is 50x faster than the list 
@ the array object is called ndarray 




In [ ]:
# why is numpy faster than lists
numpy arrays are stored at one continuous place in memory unlike list 

In [2]:
# checking numpy version 
#--version--
import numpy as np
print(np.__version__)


1.26.4


In [6]:
# the aarray object in numpy is called ndarray 
import numpy as np 
c=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[5,6,7]]])
print(c)
print(c.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [5 6 7]]]
3


In [10]:
import numpy as np 
c=np.array([[[1,23,4]],[[12,34,55]]])

print(c)
print(c.ndim)

[[[ 1 23  4]]

 [[12 34 55]]]
3


In [ ]:
# higher dimensional arrays 
an array can have any number of dimensions
we can create the number of dimensions by usinf=g the ndim


In [16]:
# createing 5 dimension 
import numpy as np
arr = np.array([1,2,3,4,4], ndmin=5)
print(arr)


[[[[[1 2 3 4 4]]]]]


In [ ]:
# numpy array indexing 
Access array elements 
array indexing is the same eas accessing an array element 


In [18]:
import numpy as np
arr = np.array([1,2,3,5])
print(arr[0])

1


In [20]:
import numpy as np
arr = np.array([1,2,3,5])
print(arr[2])

3


In [ ]:
import numpy as np
arr = np.array([1,2,3,5])
print(arr[0] + array[1]))

In [22]:
# Access 2-d arrays 
import numpy as np
arr = np.array([[1,2,3,4],[6,7,8,9]])
print('2nd element on 1st row ',arr[0,1])

2nd element on 1st row  2


In [26]:
# Access 3-d arrays 
# to access elements from 3-d arrays we can use comma separated integers representaing the dimensions 
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[1,1,2])



12


In [28]:
# negative indexing 
# use negative indexing to access an array from the end 
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('last element from 2nd dim:',arr[1,-1])

last element from 2nd dim: 10


In [ ]:
# Numpy array slicing 
Slicing in python means takeing  elements from one given index to another given index 
we pass slice instead of index like this [start:end]
wwe can also define the step like this [start:end:step]


In [30]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[1:5])

[2 3 4 5]


In [32]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,89,10])
print(arr[4:])

[ 5  6  7 89 10]


In [34]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[1:7:3])


[2 5]


In [36]:
# slicing 2 d array 
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,:4])

[6 7 8 9]


In [38]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,12]])
print(arr[0:2,2])

[3 8]


In [40]:
# difference between copy and view 
# the main difference between a copy and a view of an array is that the copy is a new array and the view is just a view of the origina; array 
import numpy as np
arr= np.array([1,2,3,4,5])
x = arr.copy()
arr[0]=42
print(arr)
print(x)
# copy should not be addected by the chages made to the original array

[42  2  3  4  5]
[1 2 3 4 5]


In [42]:
import numpy as np
arr = np.array([1,2,3,5,6,7])
x = arr.view()
arr[0]=42
print(arr)
print(x)

[42  2  3  5  6  7]
[42  2  3  5  6  7]
